version: '3'

services:
  recrutements-app:
    build: .
    ports:
      - "8082:8080"
    depends_on:
      - recrutements-postgres

  recrutements-postgres:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
    default:
        external:
          name: my-network